/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regal_class_application;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.github.sarxos.webcam.Webcam;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.util.Date;
/**
 *
 * @author omgan
 */
public class newENQUIRY extends javax.swing.JFrame implements Runnable
{

    /**
     * Creates new form addENQUIRY
     */
    Webcam webcam;
    Thread t;
    volatile boolean value;
    public newENQUIRY()
    {
        initComponents();
        webcam = Webcam.getDefault();
        webcam.setViewSize(new Dimension(320, 240));
        
    }

    public void run()
    {
        while (value)
        {
            Image img = webcam.getImage();
            if (img != null)
            {
                lblphoto.setIcon(new ImageIcon(img));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mailid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bdate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paddress = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        laddress = new javax.swing.JTextArea();
        cpytoper = new javax.swing.JButton();
        cpyback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        htown = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnmale = new javax.swing.JRadioButton();
        btnfemale = new javax.swing.JRadioButton();
        btnother = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        clgselect = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        chkall = new javax.swing.JCheckBox();
        chkjava = new javax.swing.JCheckBox();
        chkads = new javax.swing.JCheckBox();
        chkds = new javax.swing.JCheckBox();
        chkc = new javax.swing.JCheckBox();
        chkcpp = new javax.swing.JCheckBox();
        mailverify = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        crstable = new javax.swing.JTable();
        btnsubmit = new javax.swing.JButton();
        btnstart = new javax.swing.JButton();
        btncapture = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("NAME  :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnback.setBackground(new java.awt.Color(0, 102, 102));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 51));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnbackActionPerformed(evt);
            }
        });

        btnadmin.setBackground(new java.awt.Color(0, 102, 102));
        btnadmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 255, 0));
        btnadmin.setText("Admin page");
        btnadmin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnadminActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("WELOME !!!  TO THE REGAL WORLD !");
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NAME          :");

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setText("FIRST NAME");

        mname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname.setText("MIDDLE NAME");

        lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setText("LAST NAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Contact no  :");

        contactno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email :");

        mailid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mailid.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mailidActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Birth Date   :");

        bdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Local");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address       :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Permanent");

        paddress.setColumns(20);
        paddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paddress.setRows(5);
        jScrollPane2.setViewportView(paddress);

        laddress.setColumns(20);
        laddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        laddress.setRows(5);
        jScrollPane3.setViewportView(laddress);

        cpytoper.setBackground(new java.awt.Color(0, 153, 153));
        cpytoper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpytoper.setForeground(new java.awt.Color(255, 255, 0));
        cpytoper.setText(">>>");
        cpytoper.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cpytoperActionPerformed(evt);
            }
        });

        cpyback.setBackground(new java.awt.Color(0, 153, 153));
        cpyback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpyback.setForeground(new java.awt.Color(255, 255, 0));
        cpyback.setText("<<<");
        cpyback.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cpybackActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Gender :");

        htown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        htown.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("HomeTown :");

        btnmale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmale.setText("Male");
        btnmale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnmaleActionPerformed(evt);
            }
        });

        btnfemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnfemale.setText("Female");
        btnfemale.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnfemaleActionPerformed(evt);
            }
        });

        btnother.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnother.setText("Other");
        btnother.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnotherActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("College        :");

        clgselect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clgselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "PICT", "BHARTI VIDYAPITH", "VIIT", "VIT" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Subject(s) Intrested :");

        chkall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkall.setText("All");
        chkall.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkallActionPerformed(evt);
            }
        });

        chkjava.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkjava.setText("JAVA ");
        chkjava.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkjavaActionPerformed(evt);
            }
        });

        chkads.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkads.setText("ADS");
        chkads.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkadsActionPerformed(evt);
            }
        });

        chkds.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkds.setText("DS");
        chkds.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkdsActionPerformed(evt);
            }
        });

        chkc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkc.setText("C");
        chkc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkcActionPerformed(evt);
            }
        });

        chkcpp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkcpp.setText("C++");
        chkcpp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkcppActionPerformed(evt);
            }
        });

        mailverify.setBackground(new java.awt.Color(255, 0, 51));
        mailverify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mailverify.setForeground(new java.awt.Color(255, 255, 0));
        mailverify.setText("Verify");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Courses        :");

        crstable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "Mode", "C", "C++", "DS", "ADS", "Java"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(crstable);

        btnsubmit.setBackground(new java.awt.Color(255, 0, 51));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 0));
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsubmitActionPerformed(evt);
            }
        });

        btnstart.setBackground(new java.awt.Color(255, 0, 0));
        btnstart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnstart.setForeground(new java.awt.Color(255, 255, 0));
        btnstart.setText("START");
        btnstart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnstartActionPerformed(evt);
            }
        });

        btncapture.setBackground(new java.awt.Color(255, 0, 0));
        btncapture.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncapture.setForeground(new java.awt.Color(255, 255, 0));
        btncapture.setText("CAPTURE");
        btncapture.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncaptureActionPerformed(evt);
            }
        });

        lblphoto.setBackground(new java.awt.Color(0, 153, 153));
        lblphoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblphoto.setForeground(new java.awt.Color(255, 255, 255));
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setText("PHOTO");
        lblphoto.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(btnadmin)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(htown, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactno)
                                    .addComponent(bdate, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mailid, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cpytoper)
                                            .addComponent(btnmale)
                                            .addComponent(cpyback))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnfemale)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnother)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mailverify, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(142, 142, 142))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkall, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkcpp)
                                .addGap(18, 18, 18)
                                .addComponent(chkds, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnsubmit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkads, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkjava)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncapture, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(clgselect, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btncapture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailverify))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(btnmale)
                                .addComponent(btnfemale)
                                .addComponent(btnother))
                            .addComponent(bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(htown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cpytoper)
                                .addGap(18, 18, 18)
                                .addComponent(cpyback))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(clgselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkall)
                            .addComponent(chkc)
                            .addComponent(chkcpp)
                            .addComponent(chkds)
                            .addComponent(chkads)
                            .addComponent(chkjava)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsubmit)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnbackActionPerformed
    {//GEN-HEADEREND:event_btnbackActionPerformed
        try
        {
            if (evt.getSource()==btnback)
            {
                //                ENQUIRY.main(null);
                this.dispose();
            }
            else
            {
            }
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnadminActionPerformed
    {//GEN-HEADEREND:event_btnadminActionPerformed
        try
        {
            if (evt.getSource() == btnadmin)
            {
                //                ADMIN.main(null);
                this.dispose();
            }
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_btnadminActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void mailidActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mailidActionPerformed
    {//GEN-HEADEREND:event_mailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailidActionPerformed

    private void cpytoperActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cpytoperActionPerformed
    {//GEN-HEADEREND:event_cpytoperActionPerformed
        paddress.setText(laddress.getText());
    }//GEN-LAST:event_cpytoperActionPerformed

    private void cpybackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cpybackActionPerformed
    {//GEN-HEADEREND:event_cpybackActionPerformed
        paddress.setText("");
    }//GEN-LAST:event_cpybackActionPerformed

    private void btnmaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnmaleActionPerformed
    {//GEN-HEADEREND:event_btnmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmaleActionPerformed

    private void btnfemaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnfemaleActionPerformed
    {//GEN-HEADEREND:event_btnfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfemaleActionPerformed

    private void btnotherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnotherActionPerformed
    {//GEN-HEADEREND:event_btnotherActionPerformed

    }//GEN-LAST:event_btnotherActionPerformed

    private void chkallActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkallActionPerformed
    {//GEN-HEADEREND:event_chkallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkallActionPerformed

    private void chkjavaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkjavaActionPerformed
    {//GEN-HEADEREND:event_chkjavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkjavaActionPerformed

    private void chkadsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkadsActionPerformed
    {//GEN-HEADEREND:event_chkadsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkadsActionPerformed

    private void chkdsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkdsActionPerformed
    {//GEN-HEADEREND:event_chkdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkdsActionPerformed

    private void chkcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkcActionPerformed
    {//GEN-HEADEREND:event_chkcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcActionPerformed

    private void chkcppActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkcppActionPerformed
    {//GEN-HEADEREND:event_chkcppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcppActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsubmitActionPerformed
    {//GEN-HEADEREND:event_btnsubmitActionPerformed
        String Fname=fname.getText();
        String Mname=mname.getText();
        String Lname=lname.getText();
        String Contactno=contactno.getText();
        String Email=mailid.getText();
        Date Birthdate=bdate.getDate();
        String Gender = "";
        if (btnmale.isSelected())
        {
            Gender = btnmale.getText();
        }
        else if (btnfemale.isSelected())
        {
            Gender = btnfemale.getText();
        }
        else if (btnother.isSelected())
        {
            Gender = btnother.getText();
        }
        String HomeTown=htown.getText();
        String Laddress=laddress.getText();
        String Paddress=paddress.getText();
        String College=(String) clgselect.getSelectedItem();
        String Courses="";
        if (chkall.isSelected())
        {
            Courses += chkall.getText() + ", ";
        }
        else
        {
            if (chkc.isSelected())
            {
                Courses += chkc.getText() + ", ";
            }
            if (chkcpp.isSelected())
            {
                Courses += chkcpp.getText() + ", ";
            }
            if (chkds.isSelected())
            {
                Courses += chkds.getText() + ", ";
            }
            if (chkads.isSelected())
            {
                Courses += chkads.getText() + ", ";
            }
            if (chkjava.isSelected())
            {
                Courses += chkjava.getText() + ", ";
            }
        }
        String subjectsintres="abbcd";

        try
        {
            // Read the captured image file
            ImageIcon imageIcon = (ImageIcon) lblphoto.getIcon();
            Image image = imageIcon.getImage();

            // Convert the image to a byte array
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = bufferedImage.createGraphics();
            g2d.drawImage(image, 0, 0, null);
            g2d.dispose();
            ImageIO.write(bufferedImage, "jpg", baos);
            byte[] imageData = baos.toByteArray();
            File imageFile = new File("C:\\Users\\omgan\\OneDrive\\Documents\\NetBeansProjects\\practice\\src\\images\\newimage.jpg");
            FileInputStream fin = new FileInputStream(imageFile);
            /*

            create table inputdata(stid int,image longblob,Fname varchar(25),Mname varchar(25),Lname varchar(25),contact varchar(25),Email varchar(40),Bdate DATE,Gender varchar(10),Hometown varchar(20),localadd varchar(70),permadd varchar(70),college varchar(30),courses varchar(10),subjectsintres varchar(25) );
            describe inputdata;
            */
            // Save the information and image data to the database
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/practice", "root", "Mnbvcxz1@");
            PreparedStatement pst = con.prepareStatement("INSERT INTO inputdata ( image,Fname, Mname, Lname, contact, Email, Bdate, Gender, Hometown, localadd, permadd, college, courses,subjectsintres) VALUES (?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setBlob(1, fin);
            pst.setString(2, Fname);
            pst.setString(3, Mname);
            pst.setString(4, Lname);
            pst.setString(5, Contactno);
            pst.setString(6, Email);
            pst.setDate(7, new java.sql.Date(Birthdate.getTime()));
            pst.setString(8, Gender);
            pst.setString(9, HomeTown);
            pst.setString(10, Laddress);
            pst.setString(11, Paddress);
            pst.setString(12, College);
            pst.setString(13, Courses);
            pst.setString(14, subjectsintres);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Information saved!");

            fin.close();
            pst.close();
            con.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnstartActionPerformed
    {//GEN-HEADEREND:event_btnstartActionPerformed
        webcam.open();
        t = new Thread(this);
        value=true;
        t.start();
    }//GEN-LAST:event_btnstartActionPerformed

    private void btncaptureActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncaptureActionPerformed
    {//GEN-HEADEREND:event_btncaptureActionPerformed
        try
        {
            Image img = webcam.getImage();
            value=false;
            lblphoto.setIcon(new ImageIcon(img));
            ImageIO.write(webcam.getImage(), "JPG", new File("C:\\Users\\omgan\\OneDrive\\Documents\\NetBeansProjects\\practice\\src\\images\\newimage.jpg"));
            FileInputStream fin=new FileInputStream("C:\\Users\\omgan\\OneDrive\\Documents\\NetBeansProjects\\practice\\src\\images\\newimage.jpg");
            webcam.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btncaptureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(newENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(newENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(newENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(newENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public
                    void run()
            {
                new newENQUIRY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bdate;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncapture;
    private javax.swing.JRadioButton btnfemale;
    private javax.swing.JRadioButton btnmale;
    private javax.swing.JRadioButton btnother;
    private javax.swing.JButton btnstart;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JCheckBox chkads;
    private javax.swing.JCheckBox chkall;
    private javax.swing.JCheckBox chkc;
    private javax.swing.JCheckBox chkcpp;
    private javax.swing.JCheckBox chkds;
    private javax.swing.JCheckBox chkjava;
    private javax.swing.JComboBox<String> clgselect;
    private javax.swing.JTextField contactno;
    private javax.swing.JButton cpyback;
    private javax.swing.JButton cpytoper;
    private javax.swing.JTable crstable;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField htown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea laddress;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mailid;
    private javax.swing.JButton mailverify;
    private javax.swing.JTextField mname;
    private javax.swing.JTextArea paddress;
    // End of variables declaration//GEN-END:variables
}
